### ISSUE TITLE
Modal to pop up when recipe card is clicked

### ISSUE THREAD

**Issue by Adelle-Pitsas** [grainymac/whatsCookin#13]
As a user, when I click on a recipe card, I want to be able to see a pop up so that I can view more information.

**Comment by grainymac** [comment]
taken care of!

**Comment by grainymac** [comment]
you can click on the recipe card and a pop up with more information comes up.  

but a new issue that's come up is that if you click ANYWHERE on the card the modal comes up.  even when you click on the tags.  any suggestions on on what we want to try and do?

**Comment by tricia-holmes** [comment]
This has been resolved and merged into `main` 🎉
